logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.norge.patientvisit: INFO

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/patient_visit?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: mysql
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    show-sql: true

norge:
  clientApp:
         name: test

server:
  port: 8080

#  http://localhost:8080/swagger-ui/