logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.norge.patientvisit: INFO

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/patient_visit?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: mysql
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    show-sql: true

norge:
  clientApp:
         name: test
         billing: true

server:
  port: 8080

